library bank_components;

import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:flutter/cupertino.dart';
import "package:intl/intl.dart" as intel;
import 'package:shimmer/shimmer.dart';
import 'package:flutter_slidable/flutter_slidable.dart';
import 'package:persian_number_utility/persian_number_utility.dart';
import 'dart:io' show Platform;

export 'package:flutter_slidable/flutter_slidable.dart';

part 'components/spinner.dart';
part 'components/banner.dart';
part 'components/snack-bar.dart';
part 'components/transaction-item.dart';
part 'components/crypto/crypto-transaction-item.dart';
part 'components/crypto/crypto-symbol.dart';
part 'components/crypto/wallet-item.dart';
part 'components/crypto/coin-item.dart';
part 'components/crypto/market-changes.dart';
part 'components/contact-item.dart';
part 'components/notification-item.dart';
part 'components/address-item.dart';
part 'components/bottom-sheet-view.dart';
part 'components/button.dart';
part 'components/circle-button.dart';
part 'components/segmented.dart';
part 'components/chips/choice-chip.dart';
part 'components/chips/single-select-chip-row.dart';
part 'components/chips/multi-select-chip-row.dart';
part 'components/cards/zarin-card-balance.dart';
part 'components/cards/zarin-card.dart';
part 'components/cards/zarin-account-balance.dart';
part 'components/cards/custom-card-type-one.dart';
part 'components/cards/cuatom-card-type-two.dart';
part 'components/cards/zarin-account-card.dart';
part 'components/cards/profile-card.dart';
part 'components/cards/setting-card.dart';
part 'components/zarin-id.dart';
part 'components/toggle.dart';
part 'components/profile-setting-item.dart';
part 'components/textfields/textfield.dart';
part 'components/textfields/verification-textfield.dart';
part 'components/textfields/amount-textfield.dart';
part 'components/textfields/date-picker.dart';
part 'components/textfields/custom-picker.dart';
part 'components/skeleton.dart';
part 'components/appbars/main-appbar.dart';
part 'components/appbars/sub-appbar.dart';
part 'components/icon-button.dart';
part 'components/tooltip.dart';
part 'components/avatar.dart';
part 'components/price-widget.dart';
part 'components/custom-safe-area.dart';
part 'components/personal-setting-item.dart';

part 'models/action.dart';
part 'models/chip.dart';
part 'helper.dart';
